const deck = [
  {
    score: 10,
    value: "QUEEN",
    suit: "HEARTS",
    image: "http://deckofcardsapi.com/static/img/QH.png",
  },
  {
    score: 10,
    value: "QUEEN",
    suit: "DIAMONDS",
    image: "http://deckofcardsapi.com/static/img/QD.png",
  },
  {
    score: 10,
    value: "KING",
    suit: "DIAMONDS",
    image: "http://deckofcardsapi.com/static/img/KD.png",
  },
  {
    score: 7,
    value: "7",
    suit: "DIAMONDS",
    image: "http://deckofcardsapi.com/static/img/7D.png",
  },
  {
    score: 3,
    value: "3",
    suit: "HEARTS",
    image: "http://deckofcardsapi.com/static/img/3H.png",
  },
  {
    score: 7,
    value: "7",
    suit: "CLUBS",
    image: "http://deckofcardsapi.com/static/img/7C.png",
  },
  {
    score: 11,
    value: "ACE",
    suit: "CLUBS",
    image: "http://deckofcardsapi.com/static/img/AC.png",
  },
  {
    score: 10,
    value: "QUEEN",
    suit: "CLUBS",
    image: "http://deckofcardsapi.com/static/img/QC.png",
  },
  {
    score: 10,
    value: "KING",
    suit: "HEARTS",
    image: "http://deckofcardsapi.com/static/img/KH.png",
  },
  {
    score: 2,
    value: "2",
    suit: "HEARTS",
    image: "http://deckofcardsapi.com/static/img/2H.png",
  },
  {
    score: 5,
    value: "5",
    suit: "CLUBS",
    image: "http://deckofcardsapi.com/static/img/5C.png",
  },
  {
    score: 3,
    value: "3",
    suit: "SPADES",
    image: "http://deckofcardsapi.com/static/img/3S.png",
  },
  {
    score: 8,
    value: "8",
    suit: "SPADES",
    image: "http://deckofcardsapi.com/static/img/8S.png",
  },
  {
    score: 7,
    value: "7",
    suit: "SPADES",
    image: "http://deckofcardsapi.com/static/img/7S.png",
  },
  {
    score: 4,
    value: "4",
    suit: "HEARTS",
    image: "http://deckofcardsapi.com/static/img/4H.png",
  },
  {
    score: 9,
    value: "9",
    suit: "HEARTS",
    image: "http://deckofcardsapi.com/static/img/9H.png",
  },
  {
    score: 11,
    value: "ACE",
    suit: "DIAMONDS",
    image: "http://deckofcardsapi.com/static/img/AD.png",
  },
  {
    score: 11,
    value: "ACE",
    suit: "SPADES",
    image: "http://deckofcardsapi.com/static/img/AS.png",
  },
  {
    score: 9,
    value: "9",
    suit: "DIAMONDS",
    image: "http://deckofcardsapi.com/static/img/9D.png",
  },
  {
    score: 2,
    value: "2",
    suit: "SPADES",
    image: "http://deckofcardsapi.com/static/img/2S.png",
  },
  {
    score: 8,
    value: "8",
    suit: "CLUBS",
    image: "http://deckofcardsapi.com/static/img/8C.png",
  },
  {
    score: 10,
    value: "10",
    suit: "DIAMONDS",
    image: "http://deckofcardsapi.com/static/img/0D.png",
  },
  {
    score: 10,
    value: "10",
    suit: "CLUBS",
    image: "http://deckofcardsapi.com/static/img/0C.png",
  },
  {
    score: 2,
    value: "2",
    suit: "DIAMONDS",
    image: "http://deckofcardsapi.com/static/img/2D.png",
  },
  {
    score: 10,
    value: "10",
    suit: "HEARTS",
    image: "http://deckofcardsapi.com/static/img/0H.png",
  },
  {
    score: 10,
    value: "KING",
    suit: "SPADES",
    image: "http://deckofcardsapi.com/static/img/KS.png",
  },
  {
    score: 9,
    value: "9",
    suit: "SPADES",
    image: "http://deckofcardsapi.com/static/img/9S.png",
  },
  {
    score: 9,
    value: "9",
    suit: "CLUBS",
    image: "http://deckofcardsapi.com/static/img/9C.png",
  },
  {
    score: 6,
    value: "6",
    suit: "HEARTS",
    image: "http://deckofcardsapi.com/static/img/6H.png",
  },
  {
    score: 10,
    value: "10",
    suit: "SPADES",
    image: "http://deckofcardsapi.com/static/img/0S.png",
  },
  {
    score: 8,
    value: "8",
    suit: "DIAMONDS",
    image: "http://deckofcardsapi.com/static/img/8D.png",
  },
  {
    score: 4,
    value: "4",
    suit: "CLUBS",
    image: "http://deckofcardsapi.com/static/img/4C.png",
  },
  {
    score: 4,
    value: "4",
    suit: "DIAMONDS",
    image: "http://deckofcardsapi.com/static/img/4D.png",
  },
  {
    score: 6,
    value: "6",
    suit: "DIAMONDS",
    image: "http://deckofcardsapi.com/static/img/6D.png",
  },
  {
    score: 10,
    value: "KING",
    suit: "CLUBS",
    image: "http://deckofcardsapi.com/static/img/KC.png",
  },
  {
    score: 3,
    value: "3",
    suit: "DIAMONDS",
    image: "http://deckofcardsapi.com/static/img/3D.png",
  },
  {
    score: 10,
    value: "JACK",
    suit: "DIAMONDS",
    image: "http://deckofcardsapi.com/static/img/JD.png",
  },
  {
    score: 4,
    value: "4",
    suit: "SPADES",
    image: "http://deckofcardsapi.com/static/img/4S.png",
  },
  {
    score: 10,
    value: "QUEEN",
    suit: "SPADES",
    image: "http://deckofcardsapi.com/static/img/QS.png",
  },
  {
    score: 2,
    value: "2",
    suit: "CLUBS",
    image: "http://deckofcardsapi.com/static/img/2C.png",
  },
  {
    score: 5,
    value: "5",
    suit: "HEARTS",
    image: "http://deckofcardsapi.com/static/img/5H.png",
  },
  {
    score: 3,
    value: "3",
    suit: "CLUBS",
    image: "http://deckofcardsapi.com/static/img/3C.png",
  },
  {
    score: 10,
    value: "JACK",
    suit: "HEARTS",
    image: "http://deckofcardsapi.com/static/img/JH.png",
  },
  {
    score: 7,
    value: "7",
    suit: "HEARTS",
    image: "http://deckofcardsapi.com/static/img/7H.png",
  },
  {
    score: 5,
    value: "5",
    suit: "SPADES",
    image: "http://deckofcardsapi.com/static/img/5S.png",
  },
  {
    score: 6,
    value: "6",
    suit: "SPADES",
    image: "http://deckofcardsapi.com/static/img/6S.png",
  },
  {
    score: 10,
    value: "JACK",
    suit: "CLUBS",
    image: "http://deckofcardsapi.com/static/img/JC.png",
  },
  {
    score: 11,
    value: "ACE",
    suit: "HEARTS",
    image: "http://deckofcardsapi.com/static/img/AH.png",
  },
  {
    score: 10,
    value: "JACK",
    suit: "SPADES",
    image: "http://deckofcardsapi.com/static/img/JS.png",
  },
  {
    score: 5,
    value: "5",
    suit: "DIAMONDS",
    image: "http://deckofcardsapi.com/static/img/5D.png",
  },
  {
    score: 6,
    value: "6",
    suit: "CLUBS",
    image: "http://deckofcardsapi.com/static/img/6C.png",
  },
  {
    score: 8,
    value: "8",
    suit: "HEARTS",
    image: "http://deckofcardsapi.com/static/img/8H.png",
  },
];

export default deck;
